name: "Fowlie's blog"
description: "Just another blog"

plugins:
  - jekyll-paginate
  - jemoji

paginate: 30
url: "http://localhost:4000"
markdown: kramdown
highlighter: rouge
permalink: pretty

# Outputting
paginate_path: /page:num

collections:
  keyboards:
    output: true
    permalink: /:collection/:name
